### ISSUE TITLE
Docs Topics

### ISSUE THREAD

**Issue by hishamco** [oqtane/oqtane.docs#2]
@sbwalker @ADefWebserver can we start write down a roadmap of how the docs main topics should look like. I think we have a poor docs except the blogs that @ADefWebserver postes frequently.

@sbwalker could you please spend some time to write the roadmap, I'm ready to write some docs in localization, because this is one of the things are miss in Oqtane Framework

**Comment by ADefWebserver** [comment]
@hishamco - Perhaps a Discussion thread (on the [main site](https://github.com/oqtane/oqtane.framework/discussions) or here) can be created for "document wants/desires" and people in te community will start to pick them up?

For me, I know I plan to keep creating Oqtane Blog posts because I **finally** have the time to start creating Oqtane modules. However, I can only find the energy to create Blog posts if I have a **specific issue** I am up against (and it hasn't already been documented).

We really need things like the Administration features documented, but, **i** would never do them because my interest is **only** in Oqtane module development. 

Others, who perhaps do Oqtane deployments, would probably be willing to document those things.

**Comment by ADefWebserver** [comment]
Also next week I hope to start on an Oqtane Survey module. When we finally get Oqtane.org running Oqtane, we could install that module to "Take A Survey" :)

**Comment by markdav-is** [comment]
I'm interested in creating and maintaining documentation for Oqtane.   I'm currently working on onbarding docs for new devs for our enterprise app based on Oqtane.

**Comment by sbwalker** [comment]
@markdav-is I was recently able to get the rights to the content for the last DNN book published by WROX Press. I am thinking that since Oqtane has so many similarities to DNN it will jumpstart our user/developer documentation. At the very least it provides an entire table of contents, a standard documentation format, and some content to start with. There is some effort required to convert it into markdown format and upload it to the repo and I have someone who is working on it.

**Comment by iJungleboy** [comment]
@markdav-is your contributions would be awesome. 

Just fyi: the docs.oqtane.org use docfx to generate. There you can write any articles, specs etc. using markdown and you can also merge markdown with the code documentation - for example to give more information about a namespace. 

I believe that there was an issue generating the docs for .net 5.0 as it just came out, but I hope that if we spend a few hours now it should be easy to get to run.

**Comment by markdav-is** [comment]
Thanks for the updates.  I think contributing to the docs is an effective way to gain a fuller understanding of the features of the product.

**Comment by iJungleboy** [comment]
I'm going to close this as stale.
